spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master #\u914D\u7F6E\u4ED3\u5E93\u7684\u5206\u652F
      server:
        git:
          uri: https://github.com/topsale/spring-cloud-config #\u914D\u7F6E Git \u4ED3\u5E93\u5730\u5740\uFF08GitHub\u3001GitLab\u3001\u7801\u4E91 ...\uFF09
          search-paths: respo #\u914D\u7F6E\u4ED3\u5E93\u8DEF\u5F84\uFF08\u5B58\u653E\u914D\u7F6E\u6587\u4EF6\u7684\u76EE\u5F55\uFF09
          username: #\u8BBF\u95EE Git \u4ED3\u5E93\u7684\u8D26\u53F7
          password: #\u8BBF\u95EE Git \u4ED3\u5E93\u7684\u5BC6\u7801


server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
